# Generated by Django 5.2.4 on 2025-07-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('pontos', models.PositiveBigIntegerField(default=0, verbose_name='Pontos')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Avatar (URL)')),
            ],
        ),
    ]
