# Generated by Django 5.2.4 on 2025-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='personagem_favorito',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Personagem Favorito'),
        ),
    ]
